### ISSUE TITLE
Problem in generating the secret.json

### ISSUE THREAD

**Issue by Pentaonia** [maxmunzel/strichliste2.0#5]
Hey Max,

I just wanted to start the generation of the secret by "python3 init.py". Sadly I got the following error after I typed the password and hit enter:

![image](https://user-images.githubusercontent.com/93387223/201890422-51583d4a-d85f-460e-8330-397b4f85b9b8.png)

Hope you can help me with that.
I have python3 version 3.6.8.

Best
Loubert

**Comment by maxmunzel** [comment]
Hi Loubert,Maybe try removing the .encode() in line 49?Seems like the jwt lib switched to returning strings instead of bytes at some point.Cheers MaxOn 15. Nov 2022, at 11:03, Pentaonia ***@***.***> wrote:﻿
Hey Max,
I just wanted to start the generation of the secret by "python3 init.py". Sadly I got the following error after I typed the password and hit enter:

Hope you can help me with that.
I have python3 version 3.6.8.
Best
Loubert

**Comment by Pentaonia** [comment]
Hi Max,

that didnt work but when I removed the ".decode()" it runs properly.
![image](https://user-images.githubusercontent.com/93387223/201895712-1b9abed3-98d8-4a07-9837-2a24fb2ac1a3.png)



Best
Loubert

**Comment by maxmunzel** [comment]
Oh, that's also what I wanted to type ;) Happy Hacking!
